BasePackage/objects/Associate__c/Associate__c.object-meta.xml
<CustomObject>
    <label>Associate</label>
    <nameField>
        <displayFormat>Associate-{00000}</displayFormat>
        <label>Associate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InitialProject/objects/Associate__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

BasePackage/objects/Associate__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Associate__c/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <label>Nickname</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

BasePackage/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>Voucher</label>
    <nameField>
        <displayFormat>Voucher-{000000}</displayFormat>
        <label>Voucher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vouchers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BasePackage/objects/Voucher__c/fields/Associate__c.field-meta.xml
<CustomField>
    <fullName>Associate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associate</label>
    <referenceTo>Associate__c</referenceTo>
    <relationshipLabel>Vouchers</relationshipLabel>
    <relationshipName>Vouchers</relationshipName>
    <type>Lookup</type>
</CustomField>

BasePackage/objects/Voucher__c/fields/Certification_Type__c.field-meta.xml
<CustomField>
    <fullName>Certification_Type__c</fullName>
    <label>Certification Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ADM</fullName>
            </value>
            <value>
                <fullName>PD1</fullName>
            </value>
            <value>
                <fullName>Advanced ADM</fullName>
            </value>
            <value>
                <fullName>PD2</fullName>
            </value>
            <value>
                <fullName>Platform App Builder</fullName>
            </value>
            <value>
                <fullName>JS Developer 1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Base/objects/Voucher__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unused</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Voucher_Code__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Code__c</fullName>
    <label>Voucher Code</label>
    <length>128</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

BasePackage/objects/Voucher__c/fields/Voucher_Type__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Type__c</fullName>
    <label>Voucher Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Practice</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BasePackage/classes/VoucherTriggerHandler.cls
/////////////////////////////////
//
// Voucher Trigger Handler
// 
// methods:
//     OnVoucherAssignment: when an unused voucher is assigned a new user the status is changed to delivered
//     						an email is generated using the name, voucher type, code, due date, and cert type
//     						then the email is sent to the associate using their email address informing them of the assignment
//     						
// created on: 8/26/2021
// last edited: 8/26/2021
//
// This file is depricated and should be removed
// was not removed due to being included in the base package
// not enough time to test how it's removal might effect the package
// 
/////////////////////////////////

public class VoucherTriggerHandler {
    public static String messageFormat = 'To {0} {1},\nHere is your {2} {3} Voucher\nYou have until {4} to make your first attempt\nVoucher Code:{5}';
    public static void OnVoucherAssignment(List<Voucher__c> voucherList){
		List<Id> associateIds = new List<Id>();
        List<Voucher__c> changedVouchers = new List<Voucher__c>();
        for (Voucher__c curVoucher: voucherList){
            if (curVoucher.Status__c == 'Unused' && curVoucher.Associate__c != null ){
                changedVouchers.add(curVoucher);
                associateIds.add(curVoucher.Associate__c);
            }
        }
        List<Associate__c> associateList = [SELECT Id, Email__c, First_Name__c, Last_Name__c, NickName__c FROM Associate__c WHERE Id IN :associateIds];
        
        for (Associate__c curAssociate: associateList){
            for (Voucher__c curVoucher: voucherList){
                if (curVoucher.Status__c == 'Unused' && curVoucher.Associate__c == curAssociate.Id ){
                    curVoucher.Status__c = 'Delivered';
                    List<String> args = new List<String>{curAssociate.First_Name__c, curAssociate.Last_Name__c, curVoucher.Certification_Type__c, curVoucher.Voucher_Type__c, String.valueOf(curVoucher.Due_Date__c), curVoucher.Voucher_Code__c };
                    String newMessage = String.format(messageFormat,  args );
                    
                    EmailManager.sendMail(curAssociate.Email__c , 'New Voucher Assignment' , newMessage);
                    
                }
            }
        }
        
    }
}