images/objects/Associate__c/Associate__c.object-meta.xml
<CustomObject>
    <label>Associate</label>
    <nameField>
        <displayFormat>Associate-{00000}</displayFormat>
        <label>Associate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BasePackage/objects/Associate__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>Associates</relationshipLabel>
    <relationshipName>Associates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attempt__c/Attempt__c.object-meta.xml
<CustomObject>
    <label>Attempt</label>
    <nameField>
        <displayFormat>Attempt-{000000}</displayFormat>
        <label>Attempt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Base/objects/Attempt__c/fields/Attempt_Type__c.field-meta.xml
<CustomField>
    <fullName>Attempt_Type__c</fullName>
    <label>Attempt Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Practice</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BasePackage/objects/Attempt__c/fields/Passed__c.field-meta.xml
<CustomField>
    <fullName>Passed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>did you pass the exam</description>
    <label>Passed</label>
    <type>Checkbox</type>
</CustomField>

BasePackage/objects/Attempt__c/fields/Voucher__c.field-meta.xml
<CustomField>
    <fullName>Voucher__c</fullName>
    <label>Voucher</label>
    <referenceTo>Voucher__c</referenceTo>
    <relationshipLabel>Attempts</relationshipLabel>
    <relationshipName>Attempts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

InitialProject/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <displayFormat>Cohort-{0000}</displayFormat>
        <label>Cohort Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InitialProject/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>Voucher</label>
    <nameField>
        <displayFormat>Voucher-{000000}</displayFormat>
        <label>Voucher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vouchers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/fields/Associate__c.field-meta.xml
<CustomField>
    <fullName>Associate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associate</label>
    <referenceTo>Associate__c</referenceTo>
    <relationshipLabel>Vouchers</relationshipLabel>
    <relationshipName>Vouchers</relationshipName>
    <type>Lookup</type>
</CustomField>

InitialProject/objects/Voucher__c/fields/Certification_Type__c.field-meta.xml
<CustomField>
    <fullName>Certification_Type__c</fullName>
    <label>Certification Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ADM</fullName>
            </value>
            <value>
                <fullName>PD1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

D3/classes/CertificatesChartController.cls
// Author: Zackary Frazier
// Last Modify Date: 9/7/2021
// Description: Apex controller for the certificatesChart LWC

public with sharing class CertificatesChartController {
  // @desc : retrieve all associates who have earned at least one certificate
  @AuraEnabled(cacheable=true)
  public static Integer associatesWithCerts() {
    List<AggregateResult> results = [
      SELECT COUNT_DISTINCT(Voucher__r.Associate__c)
      FROM Attempt__c
      WHERE Passed__c = TRUE AND Attempt_Type__c = 'Certification'
    ];
    Integer certifiedAssociates = (Integer) results[0].get('expr0');
    return certifiedAssociates;
  }

  // @desc : retrieve number of associates who have not earned any certification
  @AuraEnabled(cacheable=true)
  public static Integer associatesWithoutCerts() {
    Integer numberOfAssociates = [SELECT COUNT() FROM Associate__c];
    Integer associatesWithoutCerts = numberOfAssociates - associatesWithCerts();
    return associatesWithoutCerts;
  }

  // @desc : retrieve all associates who have earned a specific certificate
  @AuraEnabled(cacheable=true)
  public static Integer associatesWithSpecificCert(String certType) {
    List<AggregateResult> results = [
      SELECT COUNT_DISTINCT(Voucher__r.Associate__c)
      FROM Attempt__c
      WHERE
        Passed__c = TRUE
        AND Attempt_Type__c = 'Certification'
        AND Voucher__r.Certification_Type__c = :certType
    ];
    Integer certifiedAssociates = (Integer) results[0].get('expr0');
    return certifiedAssociates;
  }

  // @desc : retrieve number of associates who have not earned a specific certification
  @AuraEnabled(cacheable=true)
  public static Integer associatesWithoutSpecificCert(String certType) {
    Integer numberOfAssociates = [SELECT COUNT() FROM Associate__c];
    Integer associatesWithoutCerts =
      numberOfAssociates - associatesWithSpecificCert(certType);
    return associatesWithoutCerts;
  }

  // @desc : retrieve all associates within a cohort who have earned at least one certificate
  @AuraEnabled(cacheable=true)
  public static Integer associatesInCohortWithCerts(String cohortName) {
    List<AggregateResult> results = [
      SELECT COUNT_DISTINCT(Voucher__r.Associate__c)
      FROM Attempt__c
      WHERE
        Passed__c = TRUE
        AND Attempt_Type__c = 'Certification'
        AND Voucher__r.Associate__r.Cohort__r.Name = :cohortName
    ];
    Integer certifiedAssociates = (Integer) results[0].get('expr0');
    return certifiedAssociates;
  }

  // @desc : retrieve number of associates in a cohort who have not earned any certification
  @AuraEnabled(cacheable=true)
  public static Integer associatesInCohortWithoutCerts(String cohortName) {
    Integer numberOfAssociates = [
      SELECT COUNT()
      FROM Associate__c
      WHERE Cohort__r.Name = :cohortName
    ];
    Integer associatesWithoutCerts =
      numberOfAssociates - associatesInCohortWithCerts(cohortName);
    return associatesWithoutCerts;
  }

  // @desc : retrieve the number of associates in a cohort who have earned a specific cert
  @AuraEnabled(cacheable=true)
  public static Integer associatesInCohortWithSpecificCert(
    String cohortName,
    String certType
  ) {
    List<AggregateResult> results = [
      SELECT COUNT_DISTINCT(Voucher__r.Associate__c)
      FROM Attempt__c
      WHERE
        Passed__c = TRUE
        AND Voucher__r.Certification_Type__c = :certType
        AND Voucher__r.Associate__r.Cohort__r.Name = :cohortName
    ];
    Integer certifiedAssociates = (Integer) results[0].get('expr0');
    return certifiedAssociates;
  }

  // @desc : retrieve the number of associates within a cohort who have not earned a specific cert
  @AuraEnabled(cacheable=true)
  public static Integer associatesInCohortWithoutSpecificCert(
    String cohortName,
    String certType
  ) {
    Integer numberOfAssociates = [
      SELECT COUNT()
      FROM Associate__c
      WHERE Cohort__r.Name = :cohortName
    ];
    Integer associatesWithoutCerts =
      numberOfAssociates -
      associatesInCohortWithSpecificCert(cohortName, certType);
    return associatesWithoutCerts;
  }

  // @desc : retrieve a list of all possible certificate types
  @AuraEnabled(cacheable=true)
  public static List<String> getCertTypes() {
    Schema.DescribeFieldResult fieldResult = Voucher__c.Certification_Type__c.getDescribe();
    List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
    List<String> picklistLabels = new List<String>();
    for (Schema.PicklistEntry entry : ple) {
      picklistLabels.add(entry.getLabel());
    }
    return picklistLabels;
  }

  // @desc : retrieve all cohort Name values
  @AuraEnabled(cacheable=true)
  public static List<String> getCohortNames() {
    List<String> cohortNames = new List<String>();
    for (Cohort__c cohort : [SELECT Name FROM Cohort__c]) {
      cohortNames.add(cohort.Name);
    }
    return cohortNames;
  }

  // @desc : given cohort id, retrieve cohort name
  @AuraEnabled(cacheable=true)
  public static String getCohortName(String id) {
    Cohort__c cohort = [SELECT Name FROM Cohort__c WHERE Id=:id];
    return cohort.Name;
  }

}