images/objects/Associate__c/Associate__c.object-meta.xml
<CustomObject>
    <label>Associate</label>
    <nameField>
        <displayFormat>Associate-{00000}</displayFormat>
        <label>Associate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BasePackage/objects/Associate__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>Associates</relationshipLabel>
    <relationshipName>Associates</relationshipName>
    <type>Lookup</type>
</CustomField>

Base/objects/Associate__c/fields/Current_Status__c.field-meta.xml
<CustomField>
    <fullName>Current_Status__c</fullName>
    <label>Current Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Staging</fullName>
            </value>
            <value>
                <fullName>Selected</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

InitialProject/objects/Associate__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

images/objects/Associate__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

images/objects/Associate__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Associates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attempt__c/Attempt__c.object-meta.xml
<CustomObject>
    <label>Attempt</label>
    <nameField>
        <displayFormat>Attempt-{000000}</displayFormat>
        <label>Attempt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Base/objects/Attempt__c/fields/Attempt_Type__c.field-meta.xml
<CustomField>
    <fullName>Attempt_Type__c</fullName>
    <label>Attempt Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Practice</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BasePackage/objects/Attempt__c/fields/Passed__c.field-meta.xml
<CustomField>
    <fullName>Passed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>did you pass the exam</description>
    <label>Passed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attempt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Taken</fullName>
            </value>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BasePackage/objects/Attempt__c/fields/Voucher__c.field-meta.xml
<CustomField>
    <fullName>Voucher__c</fullName>
    <label>Voucher</label>
    <referenceTo>Voucher__c</referenceTo>
    <relationshipLabel>Attempts</relationshipLabel>
    <relationshipName>Attempts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

InitialProject/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <displayFormat>Cohort-{0000}</displayFormat>
        <label>Cohort Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BasePackage/objects/Cohort__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

InitialProject/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>Voucher</label>
    <nameField>
        <displayFormat>Voucher-{000000}</displayFormat>
        <label>Voucher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vouchers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/fields/Associate__c.field-meta.xml
<CustomField>
    <fullName>Associate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associate</label>
    <referenceTo>Associate__c</referenceTo>
    <relationshipLabel>Vouchers</relationshipLabel>
    <relationshipName>Vouchers</relationshipName>
    <type>Lookup</type>
</CustomField>

InitialProject/objects/Voucher__c/fields/Certification_Type__c.field-meta.xml
<CustomField>
    <fullName>Certification_Type__c</fullName>
    <label>Certification Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ADM</fullName>
            </value>
            <value>
                <fullName>PD1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Base/objects/Voucher__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unused</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BasePackage/objects/Voucher__c/fields/Voucher_Type__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Type__c</fullName>
    <label>Voucher Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Practice</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

lwcInternal/classes/viewController.cls
public with sharing class viewController {
    
    // Returns a list of all cohorts
    @AuraEnabled(cacheable=true)
    public static List<Cohort__c> getCohorts() {
        return [SELECT Start_Date__c, End_Date__c FROM Cohort__c];
    }

    // Returns a list of cohorts filtered by the parameter filter
    @AuraEnabled(cacheable=true)
    public static List<Cohort__c> getFilteredCohorts(String filter) {
        String query = 'SELECT Start_Date__c, End_Date__c FROM Cohort__c';
        Date d = Date.today();
        if (filter == 'active') {
            query += ' WHERE Start_Date__c <= :d AND End_Date__c >= :d';
        } else if (filter == 'inactive') {
            query += ' WHERE Start_Date__c > :d OR End_Date__c < :d';
        }
        return Database.query(query);
    }

    // Returns a list of all associates
    @AuraEnabled(cacheable=true)
    public static List<Associate__c> getAllAssociates() {
        return getCohortAssociates(null);
    }

    // Returns a list of all associates belonging to a cohort identified by cohortId
    @AuraEnabled(cacheable=true)
    public static List<Associate__c> getCohortAssociates(Id cohortId) {
        String query = 'SELECT Id, Current_Status__c, First_Name__c, Last_Name__c, User__c, Cohort__c FROM Associate__c';
        if (cohortId != null) {
            query += ' WHERE Cohort__c = :cohortId';
        }
        return Database.query(query);
    }

    @AuraEnabled(cacheable=true)
    public static List<Associate__c> getStatusAssociates(String stat, String sortingField, String dir, Integer pageNum) {
        Integer ofst = (pageNum - 1) * 10;
        String associates = 'SELECT Id, Current_Status__c, First_Name__c, Last_Name__c, User__c, Cohort__c ' + 
        'FROM Associate__c ' + 
        'WHERE Current_Status__c = \'' + stat + '\' ' + 
        'ORDER BY ' + sortingField + ' ' + dir + ' ' + 
        'LIMIT 10 ' + 
        'OFFSET ' + ofst;
        return Database.query(associates);
    }

    public class Filters {
        @AuraEnabled
        public String searchKey { get; set; }
        @AuraEnabled
        public String[] statuses { get; set; }
        @AuraEnabled
        public String[] certs { get; set; }
    }

    @AuraEnabled(cacheable=true)
    public static List<Associate__c> getAssociates(String cohortId, Filters filters, String sortingField, String dir, Integer pageNum) {
        Integer ofst = (pageNum - 1) * 10;
        Set<Id> ids = new Set<Id>();
        if (filters != null && filters.certs != null) {
            List<Attempt__c> attempts = [SELECT Id, Attempt_Type__c, Voucher__c, Passed__c, Voucher__r.Associate__c, Voucher__r.Certification_Type__c 
        									FROM Attempt__c
        									WHERE Voucher__r.Certification_Type__c IN :filters.certs AND Passed__c = true AND Attempt_Type__c = 'Certification'];
            // A map of associate id -> list of certification filters
            // Each unique id is given a list of all requested cert types
            // Whenever an attempt with that cert type is found, it is removed
            // from that associate's list
            // An associate with an empty list has all the required certs and
            // is added to the list of ids to be searched for
            Map<Id,List<String>> filterMap = new Map<Id,List<String>>();
            for (Attempt__c att : attempts) {
                if (!filterMap.containsKey(att.Voucher__r.Associate__c)) {
                    List<String> certList = new List<String>();
                    for (String certType : filters.certs) {
                        certList.add(certType);
                    }
                    filterMap.put(att.Voucher__r.Associate__c, certList);
                }
                Integer certListIndex = filterMap.get(att.Voucher__r.Associate__c).indexOf(att.Voucher__r.Certification_Type__c);
                if (certListIndex != -1) {
                    filterMap.get(att.Voucher__r.Associate__c).remove(certListIndex);
                }
                if (filterMap.get(att.Voucher__r.Associate__c).isEmpty()) {
                    ids.add(att.Voucher__r.Associate__c);
                }
            }
        }
        String query = 'SELECT Id, Current_Status__c, First_Name__c, Last_Name__c, User__c, Cohort__c FROM Associate__c ';
        Boolean needAnd = false;
        if (cohortId != null || (filters != null && (filters.statuses != null || filters.searchKey != null || filters.certs != null))) {
            query += 'WHERE ';
        }
        if (filters != null) {
            if (!String.isEmpty(filters.searchKey)) {
                String key = '%' + filters.searchKey + '%';
                query += 'Last_Name__c LIKE :key ';
                needAnd= true;
            }
            if (filters.statuses != null) {
                if (needAnd) {
                    query += 'AND ';
                }
                String[] statuses = filters.statuses;
                query += 'Current_Status__c IN : statuses ';
                needAnd= true;
            }
            if (filters.certs != null) {
                if (needAnd) {
                    query += 'AND ';
                }
                query += 'Id IN :ids ';
                needAnd= true;
            }
        }
        if (cohortId != null) {
            if (needAnd) {
                query += 'AND ';
            }
            query += 'Cohort__c = :cohortId ';
        }
        if (sortingField != null) {
            query += 'ORDER BY ' + sortingField + ' ';
            if (dir != null) {
                query += dir + ' ';
            }
        }
        query += 'LIMIT 10 ' + 'OFFSET ' + ofst;
        return Database.query(query);
    }

    // Returns a list of all vouchers belonging to an associate identified by associateId
    @AuraEnabled(cacheable=true)
    public static List<Voucher__c> getVouchers(Id associateId) {
        return [SELECT Id, Name, Certification_Type__c, Status__c, Associate__c, Voucher_Type__c 
        FROM Voucher__c
        WHERE Associate__c =: associateId
        ORDER BY Certification_Type__c];
    }

    // Returns a list of all attempts made by an associate identified by associateId
    @AuraEnabled(cacheable=true)
    public static List<Attempt__c> getAttempts(Id associateId) {
        return [SELECT Id, Name, Attempt_Type__c, Voucher__c, Passed__c, Voucher__r.Associate__c,  Voucher__r.Name, Voucher__r.Certification_Type__c 
        FROM Attempt__c
        WHERE Voucher__r.Associate__c =: associateId
        ORDER BY Voucher__r.Certification_Type__c];
    }

    @AuraEnabled(cacheable=true)
    public static List<Attempt__c> getCertifications(Id associateId) {
        return [SELECT Id, Attempt_Type__c, Voucher__c, Passed__c, Voucher__r.Associate__c, Voucher__r.Certification_Type__c 
        FROM Attempt__c
        WHERE Voucher__r.Associate__c =: associateId AND Passed__c = true
        ORDER BY Voucher__r.Certification_Type__c];
    }

    @AuraEnabled(cacheable=true)
    public static Integer getAssociateCount(Filters filters) {
        Set<Id> ids = new Set<Id>();
        if (filters != null && filters.certs != null) {
            List<Attempt__c> attempts = [SELECT Id, Attempt_Type__c, Voucher__c, Passed__c, Voucher__r.Associate__c, Voucher__r.Certification_Type__c 
        								FROM Attempt__c
        								WHERE Voucher__r.Certification_Type__c IN :filters.certs AND Passed__c = true AND Attempt_Type__c = 'Certification'];
            // A map of associate id -> list of certification filters
            // Each unique id is given a list of all requested cert types
            // Whenever an attempt with that cert type is found, it is removed
            // from that associate's list
            // An associate with an empty list has all the required certs and
            // is added to the list of ids to be searched for
            Map<Id,List<String>> filterMap = new Map<Id,List<String>>();
            for (Attempt__c att : attempts) {
                if (!filterMap.containsKey(att.Voucher__r.Associate__c)) {
                    List<String> certList = new List<String>();
                    for (String certType : filters.certs) {
                        certList.add(certType);
                    }
                    filterMap.put(att.Voucher__r.Associate__c, certList);
                }
                Integer certListIndex = filterMap.get(att.Voucher__r.Associate__c).indexOf(att.Voucher__r.Certification_Type__c);
                if (certListIndex != -1) {
                    filterMap.get(att.Voucher__r.Associate__c).remove(certListIndex);
                }
                if (filterMap.get(att.Voucher__r.Associate__c).isEmpty()) {
                    ids.add(att.Voucher__r.Associate__c);
                }
            }
        }
        
        Boolean needAnd = false;
        String associates = 'SELECT COUNT() ' + 
        'FROM Associate__c ';
        if (filters.statuses != null || filters.searchKey != null || filters.certs != null) {
            associates += 'WHERE ';        
        }
        if (!String.isEmpty(filters.searchKey)) {
            String key = '%' + filters.searchKey + '%';
            associates += 'Last_Name__c LIKE :key ';
            needAnd= true;
        }
        if (filters.certs != null) {
            if (needAnd) {
                associates += 'AND ';
            }
            associates += 'Id IN :ids ';
            needAnd= true;
        }
        if (filters.statuses != null) {
            if (needAnd) {
                associates += 'AND ';
            }
            String[] statuses = filters.statuses;
            associates += 'Current_Status__c IN : statuses ';
            needAnd= true;
        }
        return Database.countQuery(associates);
    }
}