images/objects/Associate__c/Associate__c.object-meta.xml
<CustomObject>
    <label>Associate</label>
    <nameField>
        <displayFormat>Associate-{00000}</displayFormat>
        <label>Associate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BasePackage/objects/Associate__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>Associates</relationshipLabel>
    <relationshipName>Associates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attempt__c/Attempt__c.object-meta.xml
<CustomObject>
    <label>Attempt</label>
    <nameField>
        <displayFormat>Attempt-{000000}</displayFormat>
        <label>Attempt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Base/objects/Attempt__c/fields/Attempt_Type__c.field-meta.xml
<CustomField>
    <fullName>Attempt_Type__c</fullName>
    <label>Attempt Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Practice</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BasePackage/objects/Attempt__c/fields/Passed__c.field-meta.xml
<CustomField>
    <fullName>Passed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>did you pass the exam</description>
    <label>Passed</label>
    <type>Checkbox</type>
</CustomField>

BasePackage/objects/Attempt__c/fields/Voucher__c.field-meta.xml
<CustomField>
    <fullName>Voucher__c</fullName>
    <label>Voucher</label>
    <referenceTo>Voucher__c</referenceTo>
    <relationshipLabel>Attempts</relationshipLabel>
    <relationshipName>Attempts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

BasePackage/objects/Attempt__c/recordTypes/ADM.recordType-meta.xml
<RecordType>
    <fullName>ADM</fullName>
    <active>true</active>
    <label>Administrator</label>
</RecordType>

BasePackage/objects/Attempt__c/recordTypes/PD1.recordType-meta.xml
<RecordType>
    <fullName>PD1</fullName>
    <active>true</active>
    <label>Platform Developer I</label>
</RecordType>

InitialProject/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <displayFormat>Cohort-{0000}</displayFormat>
        <label>Cohort Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InitialProject/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>Voucher</label>
    <nameField>
        <displayFormat>Voucher-{000000}</displayFormat>
        <label>Voucher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vouchers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/fields/Associate__c.field-meta.xml
<CustomField>
    <fullName>Associate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associate</label>
    <referenceTo>Associate__c</referenceTo>
    <relationshipLabel>Vouchers</relationshipLabel>
    <relationshipName>Vouchers</relationshipName>
    <type>Lookup</type>
</CustomField>

InitialProject/objects/Voucher__c/fields/Certification_Type__c.field-meta.xml
<CustomField>
    <fullName>Certification_Type__c</fullName>
    <label>Certification Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ADM</fullName>
            </value>
            <value>
                <fullName>PD1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BasePackage/objects/Voucher__c/fields/Number_of_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Attempts__c</fullName>
    <label>Number of Attempts</label>
    <summaryForeignKey>Attempt__c.Voucher__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

BasePackage/objects/Voucher__c/fields/Voucher_Type__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Type__c</fullName>
    <label>Voucher Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Practice</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

D3/classes/AttemptChartTestController.cls
@isTest
public class AttemptChartTestController {
    

    @testSetup
    public static void setup() {
        // SETUP TAKEN FROM TESTCERTIFICATESCHARTCONTROLLER
		List<Cohort__c> cohorts = new List<Cohort__c>();
        for(Integer i = 0; i < 10; i++) {
            cohorts.add(new Cohort__c());
        }        
        insert cohorts;
        
        List<Associate__c> associates = new List<Associate__c>();
        for(Integer i  =0; i < 10; i++) {
            associates.add(new Associate__c(
            	Cohort__c = cohorts[0].Id
            ));
        }
        insert associates;
        
        List<Voucher__c> vouchers = new List<Voucher__c>();
        for(Integer i = 0; i < 10; i++) {
            vouchers.add(new Voucher__c(
                Associate__c = associates[i].Id,
                Voucher_Type__c = 'Certification',
                Certification_Type__c = (Math.mod(i, 2) == 0) ? 'ADM' : 'PD1' 
            ));
        }
        insert vouchers;
        
        List<Attempt__c> attempts = new List<Attempt__c>();
        for(Integer i = 0; i < 10; i++) {
            attempts.add(new Attempt__c(
            	Voucher__c = vouchers[i].Id,
                Attempt_Type__c = 'Certification',
                Passed__c = (Math.mod(i, 2) == 0)
            ));
        }
        insert attempts;
        
        vouchers = new List<Voucher__c>();
        for(Integer i = 0; i < 10; i++) {
            vouchers.add(new Voucher__c(
                Associate__c = associates[i].Id,
                Voucher_Type__c = 'Practice',
                Certification_Type__c = (Math.mod(i, 2) == 0) ? 'ADM' : 'PD1' 
            ));
        }
        insert vouchers;
        
        attempts = new List<Attempt__c>();
        for(Integer i = 0; i < 10; i++) {
            attempts.add(new Attempt__c(
                Voucher__c = vouchers[i].Id,
                Attempt_Type__c = 'Practice',
                Passed__c = (Math.mod(i, 2) == 0)
            ));
        }
        //insert attempts;
    }//*/

    @isTest
    public static void runTests() {
        List<Cohort__c> cList = [SELECT Name, Id FROM Cohort__c];
        List<Associate__c> aList = [SELECT Name, Id, (SELECT Name, Number_of_Attempts__c FROM Vouchers__r) FROM Associate__c WHERE Cohort__r.Id =:cList[0].Id];
        System.debug(cList);
        //System.debug(aList);
        for(Associate__c a : aList){
            System.debug(a);
            for(Voucher__c v : a.Vouchers__r){
                System.debug('mumofatt: ' + v.Number_of_Attempts__c);
            }
        }
        System.assertNotEquals(null, AttemptChartsController.getCohortById(String.valueOf(cList[1].Id)));
        System.assertNotEquals(null, AttemptChartsController.getCohortWrapperConvert(aList, 'ADM'));

        System.debug(AttemptChartsController.getCohorts());
        System.assertNotEquals(null, AttemptChartsController.getCohorts());
        System.assertNotEquals(null, AttemptChartsController.getADMOverview());
    }

    /*@isTest(SeeAllData=true)
    public static void runTestsWithLiveData(){
        List<Cohort__c> cList = [SELECT Name, Id FROM Cohort__c];
        List<Associate__c> aList = [SELECT Name, Id, (SELECT Name, Number_of_Attempts__c FROM Vouchers__r) FROM Associate__c WHERE Cohort__r.Id =:cList[0].Id];

        System.assertNotEquals(null, AttemptChartsController.getCohortById(String.valueOf(cList[1].Id)));
        System.assertNotEquals(null, AttemptChartsController.getCohortWrapperConvert(aList, 'ADM'));

        System.debug(AttemptChartsController.getCohorts());
        System.assertNotEquals(null, AttemptChartsController.getCohorts());
        System.assertNotEquals(null, AttemptChartsController.getADMOverview());
    
    }//*/
}