images/objects/Associate__c/Associate__c.object-meta.xml
<CustomObject>
    <label>Associate</label>
    <nameField>
        <displayFormat>Associate-{00000}</displayFormat>
        <label>Associate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

images/objects/Associate__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Associates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attempt__c/Attempt__c.object-meta.xml
<CustomObject>
    <label>Attempt</label>
    <nameField>
        <displayFormat>Attempt-{000000}</displayFormat>
        <label>Attempt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Base/objects/Attempt__c/fields/Attempt_Type__c.field-meta.xml
<CustomField>
    <fullName>Attempt_Type__c</fullName>
    <label>Attempt Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Practice</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BasePackage/objects/Attempt__c/fields/Passed__c.field-meta.xml
<CustomField>
    <fullName>Passed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>did you pass the exam</description>
    <label>Passed</label>
    <type>Checkbox</type>
</CustomField>

Base/objects/Attempt__c/fields/Practice_Score__c.field-meta.xml
<CustomField>
    <fullName>Practice_Score__c</fullName>
    <description>total percent score of a practice test</description>
    <label>Practice Score</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

BasePackage/objects/Attempt__c/fields/Voucher__c.field-meta.xml
<CustomField>
    <fullName>Voucher__c</fullName>
    <label>Voucher</label>
    <referenceTo>Voucher__c</referenceTo>
    <relationshipLabel>Attempts</relationshipLabel>
    <relationshipName>Attempts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

BasePackage/objects/Attempt__c/recordTypes/ADM.recordType-meta.xml
<RecordType>
    <fullName>ADM</fullName>
    <active>true</active>
    <label>Administrator</label>
</RecordType>

BasePackage/objects/Attempt__c/recordTypes/PD1.recordType-meta.xml
<RecordType>
    <fullName>PD1</fullName>
    <active>true</active>
    <label>Platform Developer I</label>
</RecordType>

BasePackage/objects/Attempt__c/recordTypes/PD2.recordType-meta.xml
<RecordType>
    <fullName>PD2</fullName>
    <active>true</active>
    <label>Platform Developer II</label>
</RecordType>

InitialProject/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>Voucher</label>
    <nameField>
        <displayFormat>Voucher-{000000}</displayFormat>
        <label>Voucher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vouchers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/fields/Associate__c.field-meta.xml
<CustomField>
    <fullName>Associate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associate</label>
    <referenceTo>Associate__c</referenceTo>
    <relationshipLabel>Vouchers</relationshipLabel>
    <relationshipName>Vouchers</relationshipName>
    <type>Lookup</type>
</CustomField>

InitialProject/objects/Voucher__c/fields/Certification_Type__c.field-meta.xml
<CustomField>
    <fullName>Certification_Type__c</fullName>
    <label>Certification Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ADM</fullName>
            </value>
            <value>
                <fullName>PD1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BasePackage/objects/Voucher__c/fields/Certified__c.field-meta.xml
<CustomField>
    <fullName>Certified__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked during approval process if and only if the certification is verified as passed</description>
    <label>Certified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Voucher_Code__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Code__c</fullName>
    <label>Voucher Code</label>
    <length>128</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

BasePackage/objects/Voucher__c/fields/Voucher_Type__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Type__c</fullName>
    <label>Voucher Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Practice</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ExperiencePackage/classes/ExperienceController.cls
public with sharing class ExperienceController {
  // ADM
  // grab the voucher for adm
  @AuraEnabled(cacheable=true)
  public static List<Voucher__c> getVoucherAdm() {
    return [
      SELECT
        id,
        Voucher_Type__c,
        Voucher_Code__c,
        Certification_Type__c,
        Associate__r.User__c
      FROM Voucher__c
      WHERE
        Certification_Type__c = 'ADM'
        AND Associate__r.User__c = :UserInfo.getUserId()
    ];
  }
  // grab the past attempts for adm
  @AuraEnabled(cacheable=true)
  public static List<Attempt__c> getPracticeAttemptsAdm() {
    return [
      SELECT
        Id,
        Attempt_Type__c,
        Passed__c,
        Practice_Score__c,
        Voucher__c,
        Voucher__r.Associate__r.User__c,
        Voucher__r.Certification_Type__c
      FROM Attempt__c
      WHERE
        Voucher__r.Certification_Type__c = 'ADM'
        AND Voucher__r.Associate__r.User__c = :UserInfo.getUserId()
    ];
  }
  // grab cert status and attempt due date for adm
  @AuraEnabled(cacheable=true)
  public static List<Voucher__c> getCertStatusAdm() {
    return [
      SELECT
        Id,
        Certified__c,
        Due_Date__c,
        Associate__r.User__c,
        Voucher_Type__c,
        Certification_Type__c
      FROM Voucher__c
      WHERE
        Associate__r.User__c = :UserInfo.getUserId()
        AND Voucher_Type__c != 'Practice'
        AND Certification_Type__c = 'Advanced ADM'
    ];
  }

  // Advanced Adm
  //grab voucher for advanced adm
  // grab the voucher for adm
  @AuraEnabled(cacheable=true)
  public static List<Voucher__c> getVoucherAdvancedAdm() {
    return [
      SELECT
        id,
        Voucher_Type__c,
        Voucher_Code__c,
        Certification_Type__c,
        Associate__r.User__c
      FROM Voucher__c
      WHERE
        Certification_Type__c = 'Advanced ADM'
        AND Associate__r.User__c = :UserInfo.getUserId()
    ];
  }
  // grab the past attempts for Advanced adm
  @AuraEnabled(cacheable=true)
  public static List<Attempt__c> getPracticeAttemptsAdvancedAdm() {
    return [
      SELECT
        Id,
        Attempt_Type__c,
        Passed__c,
        Practice_Score__c,
        Voucher__c,
        Voucher__r.Associate__r.User__c,
        Voucher__r.Certification_Type__c
      FROM Attempt__c
      WHERE
        Voucher__r.Certification_Type__c = 'Advanced ADM'
        AND Voucher__r.Associate__r.User__c = :UserInfo.getUserId()
    ];
  }
  // grab cert status and attempt due date for adv adm
  @AuraEnabled(cacheable=true)
  public static List<Voucher__c> getCertStatusAdvancedAdm() {
    return [
      SELECT
        Id,
        Certified__c,
        Due_Date__c,
        Associate__r.User__c,
        Voucher_Type__c,
        Certification_Type__c
      FROM Voucher__c
      WHERE
        Associate__r.User__c = :UserInfo.getUserId()
        AND Voucher_Type__c != 'Practice'
        AND Certification_Type__c = 'Advanced ADM'
    ];
  }

  // JavaScript
  // grab the voucher for javascript
  @AuraEnabled(cacheable=true)
  public static List<Voucher__c> getVoucherJavascr() {
    return [
      SELECT
        id,
        Voucher_Type__c,
        Voucher_Code__c,
        Certification_Type__c,
        Associate__r.User__c
      FROM Voucher__c
      WHERE
        Certification_Type__c = 'JS Developer 1'
        AND Associate__r.User__c = :UserInfo.getUserId()
    ];
  }
  // grab the past attempts for javascript
  @AuraEnabled(cacheable=true)
  public static List<Attempt__c> getPracticeAttemptsJavascr() {
    return [
      SELECT
        Id,
        Attempt_Type__c,
        Passed__c,
        Practice_Score__c,
        Voucher__c,
        Voucher__r.Associate__r.User__c,
        Voucher__r.Certification_Type__c
      FROM Attempt__c
      WHERE
        Voucher__r.Certification_Type__c = 'JS Developer 1'
        AND Voucher__r.Associate__r.User__c = :UserInfo.getUserId()
    ];
  }
  // grab cert status and attempt due date for javascript
  @AuraEnabled(cacheable=true)
  public static List<Voucher__c> getCertStatusJavascr() {
    return [
      SELECT
        Id,
        Certified__c,
        Due_Date__c,
        Associate__r.User__c,
        Voucher_Type__c,
        Certification_Type__c
      FROM Voucher__c
      WHERE
        Associate__r.User__c = :UserInfo.getUserId()
        AND Voucher_Type__c != 'Practice'
        AND Certification_Type__c = 'JS Developer 1'
    ];
  }

  // Pd1
  // grab the voucher for Pd1
  @AuraEnabled(cacheable=true)
  public static List<Voucher__c> getVoucherPd1() {
    return [
      SELECT
        id,
        Voucher_Type__c,
        Voucher_Code__c,
        Certification_Type__c,
        Associate__r.User__c
      FROM Voucher__c
      WHERE
        Certification_Type__c = 'PD1'
        AND Associate__r.User__c = :UserInfo.getUserId()
    ];
  }
  // grab the past attempts for Pd1
  @AuraEnabled(cacheable=true)
  public static List<Attempt__c> getPracticeAttemptsPd1() {
    return [
      SELECT
        Id,
        Attempt_Type__c,
        Passed__c,
        Practice_Score__c,
        Voucher__c,
        Voucher__r.Associate__r.User__c,
        Voucher__r.Certification_Type__c
      FROM Attempt__c
      WHERE
        Voucher__r.Certification_Type__c = 'PD1'
        AND Voucher__r.Associate__r.User__c = :UserInfo.getUserId()
    ];
  }
  // grab cert status and attempt due date for Pd1
  @AuraEnabled(cacheable=true)
  public static List<Voucher__c> getCertStatusPd1() {
    return [
      SELECT
        Id,
        Certified__c,
        Due_Date__c,
        Associate__r.User__c,
        Voucher_Type__c,
        Certification_Type__c
      FROM Voucher__c
      WHERE
        Associate__r.User__c = :UserInfo.getUserId()
        AND Voucher_Type__c != 'Practice'
        AND Certification_Type__c = 'PD1'
    ];
  }

  // Pd2
  // grab the voucher for Pd2
  @AuraEnabled(cacheable=true)
  public static List<Voucher__c> getVoucherPd2() {
    return [
      SELECT
        id,
        Voucher_Type__c,
        Voucher_Code__c,
        Certification_Type__c,
        Associate__r.User__c
      FROM Voucher__c
      WHERE
        Certification_Type__c = 'PD2'
        AND Associate__r.User__c = :UserInfo.getUserId()
    ];
  }
  // grab the past attempts for Pd2
  @AuraEnabled(cacheable=true)
  public static List<Attempt__c> getPracticeAttemptsPd2() {
    return [
      SELECT
        Id,
        Attempt_Type__c,
        Passed__c,
        Practice_Score__c,
        Voucher__c,
        Voucher__r.Associate__r.User__c,
        Voucher__r.Certification_Type__c
      FROM Attempt__c
      WHERE
        Voucher__r.Certification_Type__c = 'PD2'
        AND Voucher__r.Associate__r.User__c = :UserInfo.getUserId()
    ];
  }
  // grab cert status and attempt due date for Pd2
  @AuraEnabled(cacheable=true)
  public static List<Voucher__c> getCertStatusPd2() {
    return [
      SELECT
        Id,
        Certified__c,
        Due_Date__c,
        Associate__r.User__c,
        Voucher_Type__c,
        Certification_Type__c
      FROM Voucher__c
      WHERE
        Associate__r.User__c = :UserInfo.getUserId()
        AND Voucher_Type__c != 'Practice'
        AND Certification_Type__c = 'PD2'
    ];
  }
  
  // Pab
  // grab the voucher for Pab
  @AuraEnabled(cacheable=true)
  public static List<Voucher__c> getVoucherPab() {
    return [
      SELECT
        id,
        Voucher_Type__c,
        Voucher_Code__c,
        Certification_Type__c,
        Associate__r.User__c
      FROM Voucher__c
      WHERE
        Certification_Type__c = 'Platform App Builder'
        AND Associate__r.User__c = :UserInfo.getUserId()
    ];
  }
  // grab the past attempts for Pab
  @AuraEnabled(cacheable=true)
  public static List<Attempt__c> getPracticeAttemptsPab() {
    return [
      SELECT
        Id,
        Attempt_Type__c,
        Passed__c,
        Practice_Score__c,
        Voucher__c,
        Voucher__r.Associate__r.User__c,
        Voucher__r.Certification_Type__c
      FROM Attempt__c
      WHERE
        Voucher__r.Certification_Type__c = 'Platform App Builder'
        AND Voucher__r.Associate__r.User__c = :UserInfo.getUserId()
    ];
  }
  // grab cert status and attempt due date for Pab
  @AuraEnabled(cacheable=true)
  public static List<Voucher__c> getCertStatusPab() {
    return [
      SELECT
        Id,
        Certified__c,
        Due_Date__c,
        Associate__r.User__c,
        Voucher_Type__c,
        Certification_Type__c
      FROM Voucher__c
      WHERE
        Associate__r.User__c = :UserInfo.getUserId()
        AND Voucher_Type__c != 'Practice'
        AND Certification_Type__c = 'Platform App Builder'
    ];
  }
}