images/objects/Associate__c/Associate__c.object-meta.xml
<CustomObject>
    <label>Associate</label>
    <nameField>
        <displayFormat>Associate-{00000}</displayFormat>
        <label>Associate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attempt__c/Attempt__c.object-meta.xml
<CustomObject>
    <label>Attempt</label>
    <nameField>
        <displayFormat>Attempt-{000000}</displayFormat>
        <label>Attempt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BasePackage/objects/Attempt__c/fields/Passed__c.field-meta.xml
<CustomField>
    <fullName>Passed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>did you pass the exam</description>
    <label>Passed</label>
    <type>Checkbox</type>
</CustomField>

BasePackage/objects/Attempt__c/fields/Voucher__c.field-meta.xml
<CustomField>
    <fullName>Voucher__c</fullName>
    <label>Voucher</label>
    <referenceTo>Voucher__c</referenceTo>
    <relationshipLabel>Attempts</relationshipLabel>
    <relationshipName>Attempts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

InitialProject/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>Voucher</label>
    <nameField>
        <displayFormat>Voucher-{000000}</displayFormat>
        <label>Voucher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vouchers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/fields/Associate__c.field-meta.xml
<CustomField>
    <fullName>Associate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associate</label>
    <referenceTo>Associate__c</referenceTo>
    <relationshipLabel>Vouchers</relationshipLabel>
    <relationshipName>Vouchers</relationshipName>
    <type>Lookup</type>
</CustomField>

InitialProject/objects/Voucher__c/fields/Certification_Type__c.field-meta.xml
<CustomField>
    <fullName>Certification_Type__c</fullName>
    <label>Certification Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ADM</fullName>
            </value>
            <value>
                <fullName>PD1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CertificatesChartController.cls
public class CertificatesChartController {
	// @desc : retrieve all associates who have earned at least one certificate
    @AuraEnabled(cacheable=true)
    public static Integer associatesWithCerts() {
        List<AggregateResult> results = [SELECT COUNT_DISTINCT(Voucher__r.Associate__c) 
                                         FROM Attempt__c 
                                         WHERE Passed__c = True];
        Integer certifiedAssociates = (Integer) results[0].get('expr0');
        return certifiedAssociates;
    }
   
    // @desc : retrieve number of associates who have not earned any certification
    @AuraEnabled(cacheable=true)
    public static Integer associatesWithoutCerts() {
        Integer numberOfAssociates = [SELECT COUNT() FROM Associate__c];
        Integer associatesWithoutCerts = numberOfAssociates - associatesWithCerts();
        return associatesWithoutCerts;
    }
    
    // @desc : retrieve all associates who have earned a specific certificate
    @AuraEnabled(cacheable=true)
    public static Integer associatesWithSpecificCert(String certType) {
        List<AggregateResult> results = [SELECT COUNT_DISTINCT(Voucher__r.Associate__c) 
                                         FROM Attempt__c 
                                         WHERE Passed__c = True 
                                         AND Attempt__c.Voucher__r.Certification_Type__c = :certType];
        Integer certifiedAssociates = (Integer) results[0].get('expr0');
        return certifiedAssociates;
    }
    
    
    // @desc : retrieve number of associates who have not earned a specific certification
    @AuraEnabled(cacheable=true)
    public static Integer associatesWithoutSpecificCert(String certType) {
        Integer numberOfAssociates = [SELECT COUNT() FROM Associate__c];
        Integer associatesWithoutCerts = numberOfAssociates - associatesWithSpecificCert(certType);
        return associatesWithoutCerts;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<String> getCertTypes() {
        Schema.DescribeFieldResult fieldResult = Voucher__c.Certification_Type__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        List<String> picklistLabels = new List<String>();
        for(Schema.PicklistEntry entry: ple) {
            picklistLabels.add(entry.getLabel());
        }
        System.debug(picklistLabels);
        return picklistLabels;
    }
}