images/objects/Associate__c/Associate__c.object-meta.xml
<CustomObject>
    <label>Associate</label>
    <nameField>
        <displayFormat>Associate-{00000}</displayFormat>
        <label>Associate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InitialProject/objects/Associate__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attempt__c/Attempt__c.object-meta.xml
<CustomObject>
    <label>Attempt</label>
    <nameField>
        <displayFormat>Attempt-{000000}</displayFormat>
        <label>Attempt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Base/objects/Attempt__c/fields/Attempt_Type__c.field-meta.xml
<CustomField>
    <fullName>Attempt_Type__c</fullName>
    <label>Attempt Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Practice</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BasePackage/objects/Attempt__c/fields/Passed__c.field-meta.xml
<CustomField>
    <fullName>Passed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>did you pass the exam</description>
    <label>Passed</label>
    <type>Checkbox</type>
</CustomField>

Base/objects/Attempt__c/fields/Practice_Score__c.field-meta.xml
<CustomField>
    <fullName>Practice_Score__c</fullName>
    <description>total percent score of a practice test</description>
    <label>Practice Score</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

BasePackage/objects/Attempt__c/fields/textDate__c.field-meta.xml
<CustomField>
    <fullName>textDate__c</fullName>
    <formula>TEXT(Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>textDate</label>
    <type>Text</type>
</CustomField>

BasePackage/objects/Attempt__c/fields/Voucher__c.field-meta.xml
<CustomField>
    <fullName>Voucher__c</fullName>
    <label>Voucher</label>
    <referenceTo>Voucher__c</referenceTo>
    <relationshipLabel>Attempts</relationshipLabel>
    <relationshipName>Attempts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

BasePackage/objects/Attempt__c/fields/Weighted__c.field-meta.xml
<CustomField>
    <fullName>Weighted__c</fullName>
    <formula>CASE( Voucher__r.Certification_Type__c, 
      &quot;ADM&quot;, ( (Configuration_and_Setup__c * 0.2) +  
             (Object_Manager_and_Lightning_App_Builder__c * 0.2) +
             (Service_and_Support_Applications__c * 0.11) +
             (Sales_and_Marketing_Applications__c * 0.12) + 
             (Productivity_and_Collaboration__c * 0.07) + 
             (Data_and_Analytics_Management__c *0.14) + 
             (Workflow_Process_Automation__c * 0.16) ),  
      &quot;PD1&quot;, ( (Salesforce_Fundamentals__c * 0.07) + 
               (Data_Modeling_and_Management__c * 0.13) +
               (Process_Automation_and_Logic__c * 0.4) +
               (User_Interface__c * 0.23) +
               (Testing_Debugging_and_Deployment__c * 0.17) ),
      &quot;Advanced ADM&quot;, ( (Security_and_Access__c * 0.2) +
                        (Extending_Custom_Objects_and_Application__c * 0.08) +
                        (Auditing_and_Monitoring__c * 0.06) +
                        (Sales_Cloud_Applications__c * 0.1) +
                        (Service_Cloud_Applications__c * 0.1) +
                        (Data_Management__c * 0.1) +
                        (Content_Management__c * 0.03) +
                        (Change_Management__c * 0.1) +
                        (Analytics_Reports_and_Dashboards__c * 0.1) +
                        (Process_Automation__c * 0.13) ),
       &quot;PD2&quot;, ( (Salesforce_Fundamentals__c * 0.05) +
                (Data_Modeling_and_Management__c * 0.06) + 
                (Business_Logic_and_Process_Automation__c * 0.2) +
                (User_Interface__c * 0.19) +
                (Performance__c * 0.16) +
                (Integration__c * 0.15) +
                (Testing__c * 0.14) + 
                (Debug_and_Deployment_Tools__c * 0.05) ),
       &quot;Platform App Builder&quot;, ( (Salesforce_Fundamentals__c * 0.23) +
                                 (Data_Modeling_and_Management__c * 0.22) +
                                 (Business_Logic_and_Process_Automation__c * 0.28) +
                                 (User_Interface__c * 0.17) +
                                 (App_Deployment__c  * 0.1) ),
       &quot;JS Developer 1&quot;, ( (Variables_Types_and_Collections__c * 0.23) +
                           (Objects_Functions_and_Classes__c * 0.25) +
                           (Browser_and_Events__c * 0.17) +
                           (Debugging_and_Error_Handling__c * 0.07) +
                           (Asynchronous_Programming__c * 0.13) +
                           (Server_Side_JavaScript__c * 0.08) +
                           (Testing__c *0.07) ),
      0 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Approx. Weighted Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

InitialProject/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>Voucher</label>
    <nameField>
        <displayFormat>Voucher-{000000}</displayFormat>
        <label>Voucher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vouchers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/fields/Associate__c.field-meta.xml
<CustomField>
    <fullName>Associate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associate</label>
    <referenceTo>Associate__c</referenceTo>
    <relationshipLabel>Vouchers</relationshipLabel>
    <relationshipName>Vouchers</relationshipName>
    <type>Lookup</type>
</CustomField>

InitialProject/objects/Voucher__c/fields/Certification_Type__c.field-meta.xml
<CustomField>
    <fullName>Certification_Type__c</fullName>
    <label>Certification Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ADM</fullName>
            </value>
            <value>
                <fullName>PD1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BasePackage/objects/Voucher__c/fields/Eligible_By__c.field-meta.xml
<CustomField>
    <fullName>Eligible_By__c</fullName>
    <label>Eligible By</label>
    <type>Date</type>
</CustomField>

BasePackage/objects/Voucher__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Voucher_Code__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Code__c</fullName>
    <label>Voucher Code</label>
    <length>128</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

BasePackage/objects/Voucher__c/fields/Voucher_Type__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Type__c</fullName>
    <label>Voucher Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Practice</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ExperiencePackage/classes/UserAttempt.cls
public with sharing class UserAttempt {

    @AuraEnabled(cacheable=true)
    public static List<Attempt__c> getAttempts(){
        List<Attempt__c> attemptList = new List<Attempt__c>();
        attemptList = [SELECT Id, Name, Attempt_Type__c, Voucher__r.Certification_Type__c,
                       Voucher__r.Associate__r.First_Name__c,
                       textDate__c, Passed__c, Practice_Score__c, Weighted__c FROM Attempt__c];
        return attemptList;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Voucher__c> getVouchers(){
        List<Voucher__c> voucherList = new List<Voucher__c>();
        voucherList = [SELECT Id, Name, Due_Date__c, Voucher_Type__c, Voucher_Code__c,
                      Expiration_Date__c, Eligible_By__c, Certification_Type__c,
                      Associate__r.First_Name__c, (SELECT Name FROM Attempts__r) FROM Voucher__c];
        return voucherList;
    }
}