images/objects/Associate__c/Associate__c.object-meta.xml
<CustomObject>
    <label>Associate</label>
    <nameField>
        <displayFormat>Associate-{00000}</displayFormat>
        <label>Associate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BasePackage/objects/Associate__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>Associates</relationshipLabel>
    <relationshipName>Associates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attempt__c/Attempt__c.object-meta.xml
<CustomObject>
    <label>Attempt</label>
    <nameField>
        <displayFormat>Attempt-{000000}</displayFormat>
        <label>Attempt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Base/objects/Attempt__c/fields/Attempt_Type__c.field-meta.xml
<CustomField>
    <fullName>Attempt_Type__c</fullName>
    <label>Attempt Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Practice</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BasePackage/objects/Attempt__c/fields/Passed__c.field-meta.xml
<CustomField>
    <fullName>Passed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>did you pass the exam</description>
    <label>Passed</label>
    <type>Checkbox</type>
</CustomField>

BasePackage/objects/Attempt__c/fields/Voucher__c.field-meta.xml
<CustomField>
    <fullName>Voucher__c</fullName>
    <label>Voucher</label>
    <referenceTo>Voucher__c</referenceTo>
    <relationshipLabel>Attempts</relationshipLabel>
    <relationshipName>Attempts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

BasePackage/objects/Attempt__c/recordTypes/ADM.recordType-meta.xml
<RecordType>
    <fullName>ADM</fullName>
    <active>true</active>
    <label>Administrator</label>
</RecordType>

BasePackage/objects/Attempt__c/recordTypes/PD1.recordType-meta.xml
<RecordType>
    <fullName>PD1</fullName>
    <active>true</active>
    <label>Platform Developer I</label>
</RecordType>

BasePackage/objects/Attempt__c/recordTypes/PD2.recordType-meta.xml
<RecordType>
    <fullName>PD2</fullName>
    <active>true</active>
    <label>Platform Developer II</label>
</RecordType>

InitialProject/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <displayFormat>Cohort-{0000}</displayFormat>
        <label>Cohort Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InitialProject/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>Voucher</label>
    <nameField>
        <displayFormat>Voucher-{000000}</displayFormat>
        <label>Voucher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vouchers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/fields/Associate__c.field-meta.xml
<CustomField>
    <fullName>Associate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associate</label>
    <referenceTo>Associate__c</referenceTo>
    <relationshipLabel>Vouchers</relationshipLabel>
    <relationshipName>Vouchers</relationshipName>
    <type>Lookup</type>
</CustomField>

InitialProject/objects/Voucher__c/fields/Certification_Type__c.field-meta.xml
<CustomField>
    <fullName>Certification_Type__c</fullName>
    <label>Certification Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ADM</fullName>
            </value>
            <value>
                <fullName>PD1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BasePackage/objects/Voucher__c/fields/Voucher_Type__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Type__c</fullName>
    <label>Voucher Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Practice</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

D3/classes/TestCertificatesChartController.cls
// Author: Zackary Frazier
// Last Modify Date: 9/7/2021
// Description: test class for CertificatesChartController

@isTest
public class TestCertificatesChartController {
	@testSetup
    public static void setup() {
		List<Cohort__c> cohorts = new List<Cohort__c>();
        for(Integer i = 0; i < 10; i++) {
            cohorts.add(new Cohort__c());
        }        
        insert cohorts;
        
        List<Associate__c> associates = new List<Associate__c>();
        for(Integer i  =0; i < 10; i++) {
            associates.add(new Associate__c(
            	Cohort__c = cohorts[0].Id
            ));
        }
        insert associates;
        
        List<Voucher__c> vouchers = new List<Voucher__c>();
        for(Integer i = 0; i < 10; i++) {
            vouchers.add(new Voucher__c(
                Associate__c = associates[i].Id,
                Voucher_Type__c = 'Certification',
                Certification_Type__c = (Math.mod(i, 2) == 0) ? 'ADM' : 'PD1' 
            ));
        }
        insert vouchers;
        
        List<Attempt__c> attempts = new List<Attempt__c>();
        for(Integer i = 0; i < 10; i++) {
            attempts.add(new Attempt__c(
            	Voucher__c = vouchers[i].Id,
                Attempt_Type__c = 'Certification',
                Passed__c = (Math.mod(i, 2) == 0)
            ));
        }
        insert attempts;
        
        vouchers = new List<Voucher__c>();
        for(Integer i = 0; i < 10; i++) {
            vouchers.add(new Voucher__c(
                Associate__c = associates[i].Id,
                Voucher_Type__c = 'Practice',
                Certification_Type__c = (Math.mod(i, 2) == 0) ? 'ADM' : 'PD1' 
            ));
        }
        insert vouchers;
        
        attempts = new List<Attempt__c>();
        for(Integer i = 0; i < 10; i++) {
            attempts.add(new Attempt__c(
                Voucher__c = vouchers[i].Id,
                Attempt_Type__c = 'Practice',
                Passed__c = (Math.mod(i, 2) == 0)
            ));
        }
    }
    
    // positive test
    @isTest
    public static void testAssociatesWithCerts01() {
        System.assertEquals(5, CertificatesChartController.associatesWithCerts());
    }
    
    // negative test
    @isTest
    public static void testAssociatesWithCerts02() {
        // if practice tests are counted, then this would be 10
        System.assertNotEquals(10, CertificatesChartController.associatesWithCerts());
    }
    
    // positive test
    @isTest
    public static void testAssociatesWithoutCerts01() {
        // half have certs, half should not
        System.assertEquals(5, CertificatesChartController.associatesWithoutCerts());
    }
    
    // negative test
    @isTest
    public static void testAssociatesWithoutCerts02() {
        // Ensure practice tests aren't counted
        System.assertNotEquals(10, CertificatesChartController.associatesWithoutCerts());
    }
    
    // all ADMs should be passed
    @isTest
    public static void testAssociatesWithSpecificCert01() {
        System.assertEquals(5, CertificatesChartController.associatesWithSpecificCert('ADM'));
    }
    
    // all PD1s should be failed
    @isTest
    public static void testAssociatesWithSpecificCert02() {
        System.assertEquals(0, CertificatesChartController.associatesWithSpecificCert('PD1'));
    }
    
    @isTest 
    public static void testAssociatesWithoutSpecificCert01() {
        System.assertEquals(5, CertificatesChartController.associatesWithoutSpecificCert('ADM'));
    }
    
    @isTest
    public static void testAssociatesWithoutSpecificCert02() {
        System.assertEquals(10, CertificatesChartController.associatesWithoutSpecificCert('PD1'));
    }
    
    
    @isTest 
    public static void testAssociatesInCohortWithCerts01() {
        Cohort__c cohort = [SELECT Name FROM Cohort__c LIMIT 1];
        System.assertEquals(5, CertificatesChartController.associatesInCohortWithCerts(cohort.Name));
    }
    
    @isTest
    public static void testAssociatesInCohortWithCerts02() {
        Cohort__c cohort = [SELECT Name FROM Cohort__c LIMIT 1];
        System.assertNotEquals(10, CertificatesChartController.associatesInCohortWithCerts(cohort.Name));
    }
    
    @isTest
    public static void testAssociatesInCohortWithoutCerts01() {
        Cohort__c cohort = [SELECT Name FROM Cohort__c LIMIT 1];
        System.assertEquals(5, CertificatesChartController.associatesInCohortWithoutCerts(cohort.Name));
    }
    
    @isTest
    public static void testAssociatesInCohortWithoutCerts02() {
        Cohort__c cohort = [SELECT Name FROM Cohort__c LIMIT 1];
        System.assertNotEquals(10, CertificatesChartController.associatesInCohortWithoutCerts(cohort.Name));
    }
    
    @isTest
    public static void testAssociatesInCohortWithSpecificCert01() {
        List<Cohort__c> cohorts = [SELECT Name FROM Cohort__c LIMIT 2];
       	System.assertEquals(5, CertificatesChartController.associatesInCohortWithSpecificCert(cohorts[0].Name, 'ADM'));
        System.assertEquals(0, CertificatesChartController.associatesInCohortWithSpecificCert(cohorts[1].Name, 'ADM'));
    }
    
    @isTest
    public static void testAssociatesInCohortWithSpecificCert02() {
        List<Cohort__c> cohorts = [SELECT Name FROM Cohort__c LIMIT 2];
       	System.assertNotEquals(10, CertificatesChartController.associatesInCohortWithSpecificCert(cohorts[0].Name, 'ADM'));
        System.assertNotEquals(5, CertificatesChartController.associatesInCohortWithSpecificCert(cohorts[1].Name, 'ADM'));
    }
    
    @isTest
    public static void testAssociatesInCohortWithoutSpecificCert01() {
        List<Cohort__c> cohorts = [SELECT Name FROM Cohort__c LIMIT 2];
       	System.assertEquals(5, CertificatesChartController.associatesInCohortWithoutSpecificCert(cohorts[0].Name, 'ADM'));
    }
    
        @isTest
    public static void testAssociatesInCohortWithoutSpecificCert02() {
        List<Cohort__c> cohorts = [SELECT Name FROM Cohort__c LIMIT 2];
       	System.assertNotEquals(10, CertificatesChartController.associatesInCohortWithoutSpecificCert(cohorts[0].Name, 'ADM'));
    }
    
    
    // verify that the cert types are correct
    @isTest
    public static void testGetCertTypes() {
        List<String> certTypes = CertificatesChartController.getCertTypes();
        List<String> expectedTypes = new List<String>{ 'ADM', 'PD1', 'Advanced ADM', 'PD2', 'Platform App Builder', 'JS Developer 1' };
        System.assertEquals(expectedTypes.size(), certTypes.size());
        for(Integer i = 0; i < expectedTypes.size(); i++) {
            System.assertEquals(expectedTypes[i], certTypes[i]);
        }
    }
    
    @isTest
    public static void testGetCohortNames() {
        List<Cohort__c> cohorts = [SELECT Name FROM Cohort__c];
        List<String> cohortNames = CertificatesChartController.getCohortNames();
        System.assertEquals(cohorts.size(), cohortNames.size());
      	for(Cohort__c cohort: cohorts) {
            System.assert(cohortNames.contains(cohort.Name));
        }
    }
}