images/objects/Associate__c/Associate__c.object-meta.xml
<CustomObject>
    <label>Associate</label>
    <nameField>
        <displayFormat>Associate-{00000}</displayFormat>
        <label>Associate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InitialProject/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>Voucher</label>
    <nameField>
        <displayFormat>Voucher-{000000}</displayFormat>
        <label>Voucher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vouchers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/fields/Associate__c.field-meta.xml
<CustomField>
    <fullName>Associate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associate</label>
    <referenceTo>Associate__c</referenceTo>
    <relationshipLabel>Vouchers</relationshipLabel>
    <relationshipName>Vouchers</relationshipName>
    <type>Lookup</type>
</CustomField>

InitialProject/objects/Voucher__c/fields/Certification_Type__c.field-meta.xml
<CustomField>
    <fullName>Certification_Type__c</fullName>
    <label>Certification Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ADM</fullName>
            </value>
            <value>
                <fullName>PD1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Base/objects/Voucher__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unused</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BasePackage/objects/Voucher__c/fields/Voucher_Type__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Type__c</fullName>
    <label>Voucher Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Practice</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

lwcInternal/classes/VoucherAssignment.cls
public class VoucherAssignment {
    @AuraEnabled(cacheable=false)
    public static List<Associate__c> Assign(List<Associate__c> associateIds, String voucherType, String certType, Date dueDate){
		Integer numberOfVouchers = associateIds.size();
        List<Voucher__c> voucherList = [SELECT Id, Due_Date__c, Associate__c, Status__c FROM Voucher__c WHERE Associate__c = NULL AND Certification_Type__c =:certType AND Voucher_Type__c =:voucherType LIMIT :numberOfVouchers ];

        
        for(integer index = 0; index < voucherList.size(); index++){
            voucherList[index].Due_Date__c = dueDate;
            voucherList[index].Status__c = 'Delivered';

            Id curId = associateIds[0].Id;
            associateIds.remove(0);
            voucherList[index].Associate__c = Id.valueOf(curId);

        }
        database.update(voucherList);
        
        return associateIds;

    }
}