images/objects/Associate__c/Associate__c.object-meta.xml
<CustomObject>
    <label>Associate</label>
    <nameField>
        <displayFormat>Associate-{00000}</displayFormat>
        <label>Associate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BasePackage/objects/Associate__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>Associates</relationshipLabel>
    <relationshipName>Associates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attempt__c/Attempt__c.object-meta.xml
<CustomObject>
    <label>Attempt</label>
    <nameField>
        <displayFormat>Attempt-{000000}</displayFormat>
        <label>Attempt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

InitialProject/objects/Attempt__c/fields/Analytics_Reports_and_Dashboards__c.field-meta.xml
<CustomField>
    <fullName>Analytics_Reports_and_Dashboards__c</fullName>
    <label>Analytics, Reports and Dashboards</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Attempt__c/fields/App_Deployment__c.field-meta.xml
<CustomField>
    <fullName>App_Deployment__c</fullName>
    <label>App Deployment</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

InitialProject/objects/Attempt__c/fields/Asynchronous_Programming__c.field-meta.xml
<CustomField>
    <fullName>Asynchronous_Programming__c</fullName>
    <label>Asynchronous Programming</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Attempt__c/fields/Auditing_and_Monitoring__c.field-meta.xml
<CustomField>
    <fullName>Auditing_and_Monitoring__c</fullName>
    <label>Auditing and Monitoring</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

InitialProject/objects/Attempt__c/fields/Browser_and_Events__c.field-meta.xml
<CustomField>
    <fullName>Browser_and_Events__c</fullName>
    <label>Browser and Events</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

BasePackage/objects/Attempt__c/fields/Business_Logic_and_Process_Automation__c.field-meta.xml
<CustomField>
    <fullName>Business_Logic_and_Process_Automation__c</fullName>
    <label>Business Logic and Process Automation</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

InitialProject/objects/Attempt__c/fields/Change_Management__c.field-meta.xml
<CustomField>
    <fullName>Change_Management__c</fullName>
    <label>Change Management</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Attempt__c/fields/Configuration_and_Setup__c.field-meta.xml
<CustomField>
    <fullName>Configuration_and_Setup__c</fullName>
    <label>Configuration and Setup</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Base/objects/Attempt__c/fields/Content_Management__c.field-meta.xml
<CustomField>
    <fullName>Content_Management__c</fullName>
    <label>Content Management</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Attempt__c/fields/Data_and_Analytics_Management__c.field-meta.xml
<CustomField>
    <fullName>Data_and_Analytics_Management__c</fullName>
    <label>Data and Analytics Management</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Attempt__c/fields/Data_Management__c.field-meta.xml
<CustomField>
    <fullName>Data_Management__c</fullName>
    <label>Data Management</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Attempt__c/fields/Data_Modeling_and_Management__c.field-meta.xml
<CustomField>
    <fullName>Data_Modeling_and_Management__c</fullName>
    <label>Data Modeling and Management</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Attempt__c/fields/Debug_and_Deployment_Tools__c.field-meta.xml
<CustomField>
    <fullName>Debug_and_Deployment_Tools__c</fullName>
    <label>Debug and Deployment Tools</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

InitialProject/objects/Attempt__c/fields/Debugging_and_Error_Handling__c.field-meta.xml
<CustomField>
    <fullName>Debugging_and_Error_Handling__c</fullName>
    <label>Debugging and Error Handling</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

InitialProject/objects/Attempt__c/fields/Extending_Custom_Objects_and_Application__c.field-meta.xml
<CustomField>
    <fullName>Extending_Custom_Objects_and_Application__c</fullName>
    <label>Extending Custom Objects and Application</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Base/objects/Attempt__c/fields/Integration__c.field-meta.xml
<CustomField>
    <fullName>Integration__c</fullName>
    <label>Integration</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Attempt__c/fields/Object_Manager_and_Lightning_App_Builder__c.field-meta.xml
<CustomField>
    <fullName>Object_Manager_and_Lightning_App_Builder__c</fullName>
    <label>Object Manager and Lightning App Builder</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

InitialProject/objects/Attempt__c/fields/Objects_Functions_and_Classes__c.field-meta.xml
<CustomField>
    <fullName>Objects_Functions_and_Classes__c</fullName>
    <label>Objects, Functions, and Classes</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

InitialProject/objects/Attempt__c/fields/Performance__c.field-meta.xml
<CustomField>
    <fullName>Performance__c</fullName>
    <label>Performance</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

InitialProject/objects/Attempt__c/fields/Process_Automation__c.field-meta.xml
<CustomField>
    <fullName>Process_Automation__c</fullName>
    <label>Process Automation</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

InitialProject/objects/Attempt__c/fields/Process_Automation_and_Logic__c.field-meta.xml
<CustomField>
    <fullName>Process_Automation_and_Logic__c</fullName>
    <label>Process Automation and Logic</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Attempt__c/fields/Productivity_and_Collaboration__c.field-meta.xml
<CustomField>
    <fullName>Productivity_and_Collaboration__c</fullName>
    <label>Productivity and Collaboration</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

BasePackage/objects/Attempt__c/fields/Sales_and_Marketing_Applications__c.field-meta.xml
<CustomField>
    <fullName>Sales_and_Marketing_Applications__c</fullName>
    <label>Sales and Marketing Applications</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Attempt__c/fields/Sales_Cloud_Applications__c.field-meta.xml
<CustomField>
    <fullName>Sales_Cloud_Applications__c</fullName>
    <label>Sales Cloud Applications</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

InitialProject/objects/Attempt__c/fields/Salesforce_Fundamentals__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Fundamentals__c</fullName>
    <label>Salesforce Fundamentals</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Attempt__c/fields/Security_and_Access__c.field-meta.xml
<CustomField>
    <fullName>Security_and_Access__c</fullName>
    <label>Security and Access</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Attempt__c/fields/Server_Side_JavaScript__c.field-meta.xml
<CustomField>
    <fullName>Server_Side_JavaScript__c</fullName>
    <label>Server Side JavaScript</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

InitialProject/objects/Attempt__c/fields/Service_and_Support_Applications__c.field-meta.xml
<CustomField>
    <fullName>Service_and_Support_Applications__c</fullName>
    <label>Service and Support Applications</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Attempt__c/fields/Service_Cloud_Applications__c.field-meta.xml
<CustomField>
    <fullName>Service_Cloud_Applications__c</fullName>
    <label>Service Cloud Applications</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

BasePackage/objects/Attempt__c/fields/Testing__c.field-meta.xml
<CustomField>
    <fullName>Testing__c</fullName>
    <label>Testing</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

InitialProject/objects/Attempt__c/fields/Testing_Debugging_and_Deployment__c.field-meta.xml
<CustomField>
    <fullName>Testing_Debugging_and_Deployment__c</fullName>
    <label>Testing, Debugging, and Deployment</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

BasePackage/objects/Attempt__c/fields/User_Interface__c.field-meta.xml
<CustomField>
    <fullName>User_Interface__c</fullName>
    <label>User Interface</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Base/objects/Attempt__c/fields/Variables_Types_and_Collections__c.field-meta.xml
<CustomField>
    <fullName>Variables_Types_and_Collections__c</fullName>
    <label>Variables, Types, and Collections</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

BasePackage/objects/Attempt__c/fields/Voucher__c.field-meta.xml
<CustomField>
    <fullName>Voucher__c</fullName>
    <label>Voucher</label>
    <referenceTo>Voucher__c</referenceTo>
    <relationshipLabel>Attempts</relationshipLabel>
    <relationshipName>Attempts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

InitialProject/objects/Attempt__c/fields/Workflow_Process_Automation__c.field-meta.xml
<CustomField>
    <fullName>Workflow_Process_Automation__c</fullName>
    <label>Workflow/Process Automation</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

BasePackage/objects/Attempt__c/recordTypes/ADM.recordType-meta.xml
<RecordType>
    <fullName>ADM</fullName>
    <active>true</active>
    <label>Administrator</label>
</RecordType>

BasePackage/objects/Attempt__c/recordTypes/PD1.recordType-meta.xml
<RecordType>
    <fullName>PD1</fullName>
    <active>true</active>
    <label>Platform Developer I</label>
</RecordType>

BasePackage/objects/Attempt__c/recordTypes/PD2.recordType-meta.xml
<RecordType>
    <fullName>PD2</fullName>
    <active>true</active>
    <label>Platform Developer II</label>
</RecordType>

InitialProject/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <displayFormat>Cohort-{0000}</displayFormat>
        <label>Cohort Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InitialProject/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>Voucher</label>
    <nameField>
        <displayFormat>Voucher-{000000}</displayFormat>
        <label>Voucher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vouchers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/fields/Associate__c.field-meta.xml
<CustomField>
    <fullName>Associate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associate</label>
    <referenceTo>Associate__c</referenceTo>
    <relationshipLabel>Vouchers</relationshipLabel>
    <relationshipName>Vouchers</relationshipName>
    <type>Lookup</type>
</CustomField>

InitialProject/objects/Voucher__c/fields/Certification_Type__c.field-meta.xml
<CustomField>
    <fullName>Certification_Type__c</fullName>
    <label>Certification Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ADM</fullName>
            </value>
            <value>
                <fullName>PD1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

D3/classes/dataGrabber.cls
public with sharing class dataGrabber {
    
    @AuraEnabled (cacheable=true)
    public static List<String> getCerts(){
        Schema.describeFieldResult fieldResult = Voucher__c.Certification_Type__c.getDescribe();
        List<Schema.PicklistEntry> entries = fieldResult.getPicklistValues();
        List<String>picklistLabels = new List<String>();
        for(Schema.PicklistEntry newEntry : entries) {
            picklistLabels.add(newEntry.getLabel());
        }
        return picklistLabels;
    }

    @AuraEnabled (cacheable=true)
    public static List<String> getCohorts() {
        List<String> cohorts = new List<String>();
        List<Cohort__c> objects = [SELECT name FROM cohort__c];
        for (Cohort__c co : objects) {
            cohorts.add(co.name);
        }
        return cohorts;
    }
    
    @AuraEnabled (cacheable=true)
    public static List<Object> getScoresbyCohort(String jCohort, String jAttempt, Boolean jAverage) {
        List<Object> finalList = new List<Object>();
        String cohortOnly = '';
        if (jAverage == false) {
            cohortOnly = ' WHERE voucher__r.associate__r.cohort__r.name =: jCohort';
        }
        if (jAttempt == 'ADM') {
            finalList = Database.query('SELECT AVG(configuration_and_setup__c), AVG(object_manager_and_lightning_app_builder__c), AVG(sales_and_marketing_applications__c), AVG(service_and_support_applications__c), AVG(productivity_and_collaboration__c), AVG(data_and_analytics_management__c), AVG(workflow_process_automation__c) FROM attempt__c'+cohortOnly);
        } else if (jAttempt == 'PD1') {
           finalList = Database.query('SELECT AVG(salesforce_fundamentals__c), AVG(data_modeling_and_management__c), AVG(process_automation_and_logic__c), AVG(user_interface__c), AVG(testing_debugging_and_deployment__c) FROM attempt__c'+cohortOnly);
        } else if (jAttempt == 'Advanced ADM') {
            finalList = Database.query('SELECT AVG(security_and_access__c), AVG(extending_custom_objects_and_application__c), AVG(auditing_and_monitoring__c), AVG(sales_cloud_applications__c), AVG(service_cloud_applications__c), AVG(data_management__c), AVG(content_management__c), AVG(change_management__c), AVG(analytics_reports_and_dashboards__c), AVG(process_automation__c) FROM attempt__c'+cohortOnly);
        } else if (jAttempt == 'PD2') {
        	finalList = Database.query('SELECT AVG(salesforce_fundamentals__c), AVG(data_modeling_and_management__c), AVG(business_logic_and_process_automation__c), AVG(user_interface__c), AVG(performance__c), AVG(integration__c), AVG(testing__c), AVG(debug_and_deployment_tools__c) FROM attempt__c'+cohortOnly);
        } else if (jAttempt == 'Platform App Builder') {
            finalList = Database.query('SELECT AVG(salesforce_fundamentals__c), AVG(data_modeling_and_management__c), AVG(business_logic_and_process_automation__c), AVG(user_interface__c), AVG(app_deployment__c) FROM attempt__c'+cohortOnly);
        } else if (jAttempt == 'JS Developer 1') {
            finalList = Database.query('SELECT AVG(variables_types_and_collections__c), AVG(objects_functions_and_classes__c), AVG(browser_and_events__c), AVG(debugging_and_error_handling__c), AVG(asynchronous_programming__c), AVG(server_side_javascript__c), AVG(testing__c) FROM attempt__c'+cohortOnly);
        } else {
            finalList = [SELECT id FROM attempt__c LIMIT 1];
        }
        return finalList;
    }

}