BasePackage/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>Voucher</label>
    <nameField>
        <displayFormat>Voucher-{000000}</displayFormat>
        <label>Voucher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vouchers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BasePackage/objects/Voucher__c/fields/Max_Date__c.field-meta.xml
<CustomField>
    <fullName>Max_Date__c</fullName>
    <label>Max Date</label>
    <summarizedField>Attempt__c.CreatedDate</summarizedField>
    <summaryForeignKey>Attempt__c.Voucher__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

BasePackage/objects/Voucher__c/fields/Number_of_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Attempts__c</fullName>
    <label>Number of Attempts</label>
    <summaryForeignKey>Attempt__c.Voucher__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

BasePackage/classes/VoucherController.cls
// This file is depricated and should be removed
// was not removed due to being included in the base package
// not enough time to test how it's removal might effect the package

public class VoucherController {
    
	@AuraEnabled
    public static String GetEligibility(Id VoucherId){
        Voucher__c curVoucher = [SELECT Max_Date__c, Number_of_Attempts__c FROM Voucher__c WHERE Id =:VoucherId];
        return 'functional';
    }
}