InitialProject/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <displayFormat>Cohort-{0000}</displayFormat>
        <label>Cohort Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InitialProject/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>Voucher</label>
    <nameField>
        <displayFormat>Voucher-{000000}</displayFormat>
        <label>Voucher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vouchers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InitialProject/objects/Voucher__c/fields/Certification_Type__c.field-meta.xml
<CustomField>
    <fullName>Certification_Type__c</fullName>
    <label>Certification Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ADM</fullName>
            </value>
            <value>
                <fullName>PD1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

D3/main/default/classes/dataGrabber.cls
public with sharing class dataGrabber {
    
    @AuraEnabled (cacheable=true)
    public static List<String> getCerts(){
        Schema.describeFieldResult fieldResult = Voucher__c.Certification_Type__c.getDescribe();
        List<Schema.PicklistEntry> entries = fieldResult.getPicklistValues();
        List<String>picklistLabels = new List<String>();
        for(Schema.PicklistEntry newEntry : entries) {
            picklistLabels.add(newEntry.getLabel());
        }
        return picklistLabels;
    }

    @AuraEnabled (cacheable=true)
    public static List<String> getCohorts() {
        List<String> cohorts = new List<String>();
        List<Cohort__c> objects = [SELECT name FROM cohort__c];
        for (Cohort__c co : objects) {
            cohorts.add(co.name);
        }
        return cohorts;
    }

}