BasePackage/objects/Attempt__c/Attempt__c.object-meta.xml
<CustomObject>
    <label>Attempt</label>
    <nameField>
        <displayFormat>Attempt-{000000}</displayFormat>
        <label>Attempt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Base/objects/Attempt__c/fields/Attempt_Type__c.field-meta.xml
<CustomField>
    <fullName>Attempt_Type__c</fullName>
    <label>Attempt Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Practice</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BasePackage/objects/Attempt__c/fields/Voucher__c.field-meta.xml
<CustomField>
    <fullName>Voucher__c</fullName>
    <label>Voucher</label>
    <referenceTo>Voucher__c</referenceTo>
    <relationshipLabel>Attempts</relationshipLabel>
    <relationshipName>Attempts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

BasePackage/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>Voucher</label>
    <nameField>
        <displayFormat>Voucher-{000000}</displayFormat>
        <label>Voucher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vouchers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BasePackage/objects/Voucher__c/fields/Eligible_By__c.field-meta.xml
<CustomField>
    <fullName>Eligible_By__c</fullName>
    <label>Eligible By</label>
    <type>Date</type>
</CustomField>

BasePackage/objects/Voucher__c/fields/Max_Date__c.field-meta.xml
<CustomField>
    <fullName>Max_Date__c</fullName>
    <label>Max Date</label>
    <summarizedField>Attempt__c.CreatedDate</summarizedField>
    <summaryForeignKey>Attempt__c.Voucher__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

BasePackage/objects/Voucher__c/fields/Number_of_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Attempts__c</fullName>
    <label>Number of Attempts</label>
    <summaryForeignKey>Attempt__c.Voucher__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

BasePackage/classes/AttemptTriggerHandler.cls
public class AttemptTriggerHandler {
    
    public static List<Integer> daysLimit = new List<Integer>{0,1,14,0,1,14};
    public static void setEligibility(List<Attempt__c> attemptList){
        List<Id> voucherIdList = new List<Id>();
        for (Attempt__c curAttempt : attemptList){
            if(curAttempt.Attempt_Type__c == 'Certification' ){
                voucherIdList.add(curAttempt.Voucher__c);
            }
        }
        List<Voucher__c> voucherList = [SELECT Max_Date__c, Number_of_Attempts__c, Eligible_By__c FROM Voucher__c WHERE Id IN :voucherIdList ];
        for( Voucher__c curVoucher : voucherList ){
            system.assert(True, curVoucher.Number_of_Attempts__c);
            if (curVoucher.Number_of_Attempts__c > 0){
                DateTime dT = curVoucher.Max_Date__c;
                DateTime ndt = dt.addDays(daysLimit[Integer.valueof(curVoucher.Number_of_Attempts__c)] );
                Date myDate = date.newinstance(ndT.year(), ndT.month(), ndT.day());
                curVoucher.Eligible_By__c = myDate;
            }else{
                curVoucher.Eligible_By__c = system.today();
            }
        }
        database.update(voucherList);
    }
}